# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1THwnbva6EBr8-H4KbUH8h8Wkp2kRGwcc
"""

import whisper
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
from gtts import gTTS
import torch
from scipy.io.wavfile import write
import numpy as np

# -------------------------
# LOAD MODELS
# -------------------------
device = "cuda" if torch.cuda.is_available() else "cpu"

# Whisper (Speech → Text)
whisper_model = whisper.load_model("tiny")

# NLLB (Translation)
model_name = "facebook/nllb-200-distilled-600M"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name).to(device)

# -------------------------
# LANGUAGE MAP
# -------------------------
lang_map = {
    "Hindi": ("eng_Latn", "hin_Deva", "hi"),
    "Malayalam": ("eng_Latn", "mal_Mlym", "ml"),
    "Tamil": ("eng_Latn", "tam_Taml", "ta"),
    "Telugu": ("eng_Latn", "tel_Telu", "te"),
    "Kannada": ("eng_Latn", "kan_Knda", "kn"),
}

# -------------------------
# FUNCTIONS
# -------------------------

def save_audio(audio_np, filename="temp.wav"):
    audio_np = audio_np.astype("float32")

    if len(audio_np.shape) > 1:
        audio_np = audio_np.mean(axis=1)

    write(filename, 16000, audio_np)
    return filename


def speech_to_text(audio_file):
    result = whisper_model.transcribe(audio_file, fp16=False)
    return result["text"]


def translate(text, src_lang, tgt_lang):
    tokenizer.src_lang = src_lang

    inputs = tokenizer(text, return_tensors="pt", truncation=True).to(device)

    outputs = model.generate(
        **inputs,
        forced_bos_token_id=tokenizer.lang_code_to_id[tgt_lang],
        max_length=200
    )

    return tokenizer.decode(outputs[0], skip_special_tokens=True)


def text_to_speech(text, lang_code):
    filename = "output.mp3"
    tts = gTTS(text=text, lang=lang_code)
    tts.save(filename)
    return filename

